/**
 * Cervinodata API documentation
 * <div style='margin: 2em 0;'> <p> Before you get going with the Cervinodata API, set up Cervinodata (read the support page here: <a href='https://support.cervinodata.com/hc/en-nl/articles/360004363237' target='_blank'>How to set up the Cervinodata API</a>). </p> <h3>To use the Cervinodata API, you need all of the following:</h3> <p> <ol> <li>An active Cervinodata account, you can start a free trial <a href='https://app.cervinodata.com/register' target='_blank'>here</a></li> <li>At least one connection to a platform (check <a href='https://app.cervinodata.com/data-sources-connections' target='_blank'>here</a>)</li> <li>At least one account switched ON (check <a href='https://app.cervinodata.com/accounts' target='_blank'>here</a>)</li> <li>At least one data refresh executed (check <a href='https://app.cervinodata.com/manual-data-refresh' target='_blank'>here</a>)</li> <li>An active API token (check <a href='https://app.cervinodata.com/settings#/api' target='_blank'>here</a>)</li> </ol> </p> <p> Note that limits apply for <a href='https://support.cervinodata.com/hc/articles/360014265139' target='_blank'>Free plan users</a>. </p> <p> If you wish to automate your Cervinodata API connection, check out the list of client API's at <a href='https://github.com/Cervinodata' target='_blank'>https://github.com/Cervinodata</a>. </p> </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cervinodata.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* AnalyticsDataDefaultMetrics service.
* @module api/AnalyticsDataDefaultMetricsApi
* @version 0.1.0
*/
export default class AnalyticsDataDefaultMetricsApi {

    /**
    * Constructs a new AnalyticsDataDefaultMetricsApi. 
    * @alias module:api/AnalyticsDataDefaultMetricsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAnalyticsReportPerCampaignPerDay operation.
     * @callback module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerCampaignPerDayCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return analytics report per campaign per day by organisation
     * Analytics report per campaign per day by organisation
     * @param {String} organisationUuid Organisation uuid
     * @param {Object} opts Optional parameters
     * @param {Date} opts.fromDate From date
     * @param {module:model/String} opts.dateFormat Outputted date format
     * @param {module:model/String} opts.format Output format (use csv for large result sets)
     * @param {module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerCampaignPerDayCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    getAnalyticsReportPerCampaignPerDay(organisationUuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'organisationUuid' is set
      if (organisationUuid === undefined || organisationUuid === null) {
        throw new Error("Missing the required parameter 'organisationUuid' when calling getAnalyticsReportPerCampaignPerDay");
      }

      let pathParams = {
        'organisationUuid': organisationUuid
      };
      let queryParams = {
        'from_date': opts['fromDate'],
        'date_format': opts['dateFormat'],
        'format': opts['format']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['text/csv', 'application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/data/analytics-report-per-campaign-per-day/{organisationUuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAnalyticsReportPerChannelGroupPerDay operation.
     * @callback module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerChannelGroupPerDayCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return analytics report per channel group per day by organisation
     * Analytics report per channel group per day by organisation
     * @param {String} organisationUuid Organisation uuid
     * @param {Object} opts Optional parameters
     * @param {Date} opts.fromDate From date
     * @param {module:model/String} opts.dateFormat Outputted date format
     * @param {module:model/String} opts.format Output format (use csv for large result sets)
     * @param {module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerChannelGroupPerDayCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    getAnalyticsReportPerChannelGroupPerDay(organisationUuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'organisationUuid' is set
      if (organisationUuid === undefined || organisationUuid === null) {
        throw new Error("Missing the required parameter 'organisationUuid' when calling getAnalyticsReportPerChannelGroupPerDay");
      }

      let pathParams = {
        'organisationUuid': organisationUuid
      };
      let queryParams = {
        'from_date': opts['fromDate'],
        'date_format': opts['dateFormat'],
        'format': opts['format']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['text/csv', 'application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/data/analytics-report-per-channel-group-per-day/{organisationUuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAnalyticsReportPerDevicePerChannelGroupPerOrganisationPerViewPerDay operation.
     * @callback module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerDevicePerChannelGroupPerOrganisationPerViewPerDayCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return analytics report per device per channel group per organisation per view per day
     * Analytics report per device per channel group per organisation per view per day
     * @param {Array.<String>} organisationUuids Organisation uuids
     * @param {Object} opts Optional parameters
     * @param {Date} opts.fromDate From date
     * @param {module:model/String} opts.dateFormat Outputted date format
     * @param {module:model/String} opts.format Output format (use csv for large result sets)
     * @param {module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerDevicePerChannelGroupPerOrganisationPerViewPerDayCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    getAnalyticsReportPerDevicePerChannelGroupPerOrganisationPerViewPerDay(organisationUuids, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'organisationUuids' is set
      if (organisationUuids === undefined || organisationUuids === null) {
        throw new Error("Missing the required parameter 'organisationUuids' when calling getAnalyticsReportPerDevicePerChannelGroupPerOrganisationPerViewPerDay");
      }

      let pathParams = {
        'organisationUuids': organisationUuids
      };
      let queryParams = {
        'from_date': opts['fromDate'],
        'date_format': opts['dateFormat'],
        'format': opts['format']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['text/csv', 'application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/data/analytics-report-per-device-per-channel-group-per-organisation-per-view-per-day/{organisationUuids}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAnalyticsReportPerDevicePerDay operation.
     * @callback module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerDevicePerDayCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return analytics report per device per day by organisation
     * Analytics report per device per day by organisation
     * @param {String} organisationUuid Organisation uuid
     * @param {Object} opts Optional parameters
     * @param {Date} opts.fromDate From date
     * @param {module:model/String} opts.dateFormat Outputted date format
     * @param {module:model/String} opts.format Output format (use csv for large result sets)
     * @param {module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerDevicePerDayCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    getAnalyticsReportPerDevicePerDay(organisationUuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'organisationUuid' is set
      if (organisationUuid === undefined || organisationUuid === null) {
        throw new Error("Missing the required parameter 'organisationUuid' when calling getAnalyticsReportPerDevicePerDay");
      }

      let pathParams = {
        'organisationUuid': organisationUuid
      };
      let queryParams = {
        'from_date': opts['fromDate'],
        'date_format': opts['dateFormat'],
        'format': opts['format']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['text/csv', 'application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/data/analytics-report-per-device-per-day/{organisationUuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAnalyticsReportPerSourceMediumPerDay operation.
     * @callback module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerSourceMediumPerDayCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return analytics report per source medium per day by organisation
     * Analytics report per source medium per day by organisation
     * @param {String} organisationUuid Organisation uuid
     * @param {Object} opts Optional parameters
     * @param {Date} opts.fromDate From date
     * @param {module:model/String} opts.dateFormat Outputted date format
     * @param {module:model/String} opts.format Output format (use csv for large result sets)
     * @param {module:api/AnalyticsDataDefaultMetricsApi~getAnalyticsReportPerSourceMediumPerDayCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    getAnalyticsReportPerSourceMediumPerDay(organisationUuid, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'organisationUuid' is set
      if (organisationUuid === undefined || organisationUuid === null) {
        throw new Error("Missing the required parameter 'organisationUuid' when calling getAnalyticsReportPerSourceMediumPerDay");
      }

      let pathParams = {
        'organisationUuid': organisationUuid
      };
      let queryParams = {
        'from_date': opts['fromDate'],
        'date_format': opts['dateFormat'],
        'format': opts['format']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['text/csv', 'application/json'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/data/analytics-report-per-source-medium-per-day/{organisationUuid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
