/**
 * Cervinodata API documentation
 * <div style='margin: 2em 0;'><p>Before you get going with the Cervinodata API, set up Cervinodata (read the support page here: <a href='https://support.cervinodata.com/hc/en-nl/articles/360004363237' target='_blank'>How to set up the Cervinodata API</a>).</p> <h3>To use the Cervinodata API, you need all of the following:</h3> <p> <ol> <li>An active Cervinodata account, you can start a free trial <a href='https://app.cervinodata.com/register' target='_blank'>here</a></li> <li>At least one connection to a platform (check <a href='https://app.cervinodata.com/pages/data-sources/connections' target='_blank'>here</a>)</li> <li>At least one account switched ON (check <a href='https://app.cervinodata.com/pages/data-sources/accounts' target='_blank'>here</a>)</li> <li>At least one data refresh executed (check <a href='https://app.cervinodata.com/pages/data-destinations-api/data-collection' target='_blank'>here</a>)</li> <li>An active API token (check <a href='https://app.cervinodata.com/settings#/api' target='_blank'>here</a>)</li> </ol> </p> <p> If you wish to automate your Cervinodata API connection, check out the list of client API's at <a href='https://github.com/Cervinodata' target='_blank'>https://github.com/Cervinodata</a>. </p> </div>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cervinodata.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CervinodataApiClient);
  }
}(this, function(expect, CervinodataApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CervinodataApiClient.AnalyticsDataGoalsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AnalyticsDataGoalsApi', function() {
    describe('getAnalyticsGoalReportPerCampaignPerDay', function() {
      it('should call getAnalyticsGoalReportPerCampaignPerDay successfully', function(done) {
        //uncomment below and update the code to test getAnalyticsGoalReportPerCampaignPerDay
        //instance.getAnalyticsGoalReportPerCampaignPerDay(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnalyticsGoalReportPerChannelGroupPerDay', function() {
      it('should call getAnalyticsGoalReportPerChannelGroupPerDay successfully', function(done) {
        //uncomment below and update the code to test getAnalyticsGoalReportPerChannelGroupPerDay
        //instance.getAnalyticsGoalReportPerChannelGroupPerDay(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnalyticsGoalReportPerDevicePerChannelGroupPerOrganisationPerViewPerDay', function() {
      it('should call getAnalyticsGoalReportPerDevicePerChannelGroupPerOrganisationPerViewPerDay successfully', function(done) {
        //uncomment below and update the code to test getAnalyticsGoalReportPerDevicePerChannelGroupPerOrganisationPerViewPerDay
        //instance.getAnalyticsGoalReportPerDevicePerChannelGroupPerOrganisationPerViewPerDay(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnalyticsGoalReportPerDevicePerDay', function() {
      it('should call getAnalyticsGoalReportPerDevicePerDay successfully', function(done) {
        //uncomment below and update the code to test getAnalyticsGoalReportPerDevicePerDay
        //instance.getAnalyticsGoalReportPerDevicePerDay(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnalyticsGoalReportPerSourceMediumPerDay', function() {
      it('should call getAnalyticsGoalReportPerSourceMediumPerDay successfully', function(done) {
        //uncomment below and update the code to test getAnalyticsGoalReportPerSourceMediumPerDay
        //instance.getAnalyticsGoalReportPerSourceMediumPerDay(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
